[package]
name = "ecsl_source"
version = "0.1.0"
edition = "2021"

[dependencies]
ecsl_error = { path = "../ecsl_error" }
ecsl_span = { path = "../ecsl_span" }
ecsl_diagnostic = { path = "../ecsl_diagnostic"}