[package]
name = "ecsl_source"
version = "0.1.0"
edition = "2021"

[dependencies]
ecsl_error = { path = "../ecsl_error" }
ecsl_index = { path = "../ecsl_index" }
ecsl_diagnostics = { path = "../ecsl_diagnostics"}
cfgrammar = "0.13"