[workspace]
members = [
    "bundle",
    "ecsl_config",
    "ecsl_context",
    "ecsl_diagnostics",
    "ecsl_driver",
    "ecsl_error",
    "ecsl_lexer",
    "ecsl_ast",
    "ecsl_source",
    "ecsl_span"
]
resolver = "1"
