[workspace]
members = [
    "bundle",
    "ecsl_bytecode",
    "ecsl_config",
    "ecsl_context",
    "ecsl_diagnostics",
    "ecsl_driver",
    "ecsl_error",
    "ecsl_ast",
    "ecsl_source",
    "ecsl_index",
    "ecsl_parse"
    "ecsl_assembler",
    "ecsl_lexer",
    "ecsl_source",
    ]

resolver = "1"
