[package]
name = "ecsl_lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
ecsl_diagnostics = { path = "../ecsl_diagnostics" }
ecsl_error = { path = "../ecsl_error" }
ecsl_index = { path = "../ecsl_index" }
ecsl_context = { path = "../ecsl_context" }
ecsl_source = { path = "../ecsl_source" }