[package]
name = "ecsl_test_runner"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.6"
glob = "0.3.1"
anyhow = "1.0.86"
ecsl_diagnostics = { path = "../ecsl_diagnostics" }
ecsl_error = { path = "../ecsl_error" }
log.workspace = true
