[package]
name = "ecsl_gir"
version = "0.1.0"
edition = "2021"

[dependencies]
ecsl_index = { path = "../ecsl_index" }
ecsl_ty = { path = "../ecsl_ty" }
ecsl_ast = { path = "../ecsl_ast" }
petgraph = "0.6.5"
cfgrammar.workspace = true
log.workspace = true
